#version 440

// Generated by tools/gen.py -- do not edit by hand.
//
// Deep zoom at the Misiurewicz point
//   c = 0.44875200192771446750740747705655009586423028788517681498994155046380055589295755710187482737786736596958923807291747552731092458246361170625993575377226687341881250418810616985206035537551914998445167024439573937159162897917278555027940611184253682282420450775 + 0.23075928523387156042167891696202629517855868245181600328661030844667776091054058795438392937149571730412005271957831861710305213663028384646201555087702322965762066023278423133725051110387854875379280324213599522516628828011296611255150914576320822576095976856i
// preperiod 4, period 4, |lambda| = 25.725175,
// arg(lambda)/2pi = 0.040314454.
//
// The reference orbit is preperiodic, so it is a table of 8 values that
// repeats forever.  Perturbation then keeps every pixel's own arithmetic small:
// eps is the pixel's offset from the reference and starts at the view width, so
// the same float work renders the view at any depth.  The escape count is
// bounded because the reference never escapes, so raising the zoom costs
// nothing at all.

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;

    float uPhase;       // position in the loop, [0,1)
    float uAspect;      // height / width
    float uPalScale;    // multiplier on the band frequency baked in below

    vec4 uPal0;
    vec4 uPal1;
    vec4 uPal2;
    vec4 uPal3;
};

#define CYCLES 34          // whole periods actually iterated

// The point's own constants, baked in: nothing outside this file needs to know
// them, and the camera must match them exactly or the loop will not close.
#define OCT_PER_LOOP 4.685109002595416    // log2 |lambda|, octaves of zoom per loop
#define ROT_PER_LOOP 0.9596855459467597    // 1 - arg(lambda)/2pi, turns per loop
#define PAL_SCALE 0.044723      // palette cycles per escape step, from the point's own range
#define PAL_OFFSET 18.694     // escape count that sits on the first palette stop
#define DRIFT 4         // escape steps gained over one loop, == period
#define HALF_W0 5.960464477539062e-07       // half width of the view at phase 0
#define TWO_PI 6.283185307179586

const vec2 ORB[8] = vec2[8](
    vec2(0.0, 0.0),
    vec2(0.4487520019277145, 0.23075928523387157),
    vec2(0.5968805134401987, 0.43786666765808824),
    vec2(0.6132911306063509, 0.7534674480540886),
    vec2(0.2571648175309899, 1.1549490914182194),
    vec2(-0.819021658464309, 0.8247838299381696),
    vec2(0.4392801128338662, -1.1202723553071368),
    vec2(-0.6132911306063509, -0.7534674480540886));

const float LOG2 = 0.6931471805599453;

vec4 palette(float t) {
    // Cyclic four stop ramp.
    float x = fract(t) * 4.0;
    vec4 a = uPal0, b = uPal1;
    if (x >= 3.0)      { a = uPal3; b = uPal0; x -= 3.0; }
    else if (x >= 2.0) { a = uPal2; b = uPal3; x -= 2.0; }
    else if (x >= 1.0) { a = uPal1; b = uPal2; x -= 1.0; }
    return mix(a, b, smoothstep(0.0, 1.0, x));
}

void main() {
    vec2 t = qt_TexCoord0;
    vec2 uv = vec2(t.x * 2.0 - 1.0, 1.0 - t.y * 2.0);
    uv.y *= uAspect;

    float halfw = HALF_W0 * exp2(-uPhase * OCT_PER_LOOP);

    float ang = uPhase * ROT_PER_LOOP * TWO_PI;
    float ca = cos(ang), sa = sin(ang);
    vec2 d = vec2(uv.x * ca - uv.y * sa, uv.x * sa + uv.y * ca) * halfw;

    vec2 e = vec2(0.0);
    float iter = 0.0;
    bool esc = false;
    float m2 = 0.0;
    vec2 zn;

#define STEP(I) { \
        zn = ORB[I]; \
        e = vec2(2.0 * (zn.x * e.x - zn.y * e.y) + e.x * e.x - e.y * e.y + d.x, \
                 2.0 * (zn.y * e.x + zn.x * e.y) + 2.0 * e.x * e.y + d.y); \
        iter += 1.0; \
        m2 = dot(e, e); \
        if (m2 > 65536.0) esc = true; \
    }

    // preperiod: a straight run of literal indices
    if (!esc) STEP(0);
    if (!esc) STEP(1);
    if (!esc) STEP(2);
    if (!esc) STEP(3);

    // then whole periods, again with literal indices, so nothing is indexed by a
    // computed value.  Breaking on escape matters: continuing to iterate an
    // escaped pixel squares it past float range and poisons the colour.
    for (int cycle = 0; cycle < CYCLES; cycle++) {
        STEP(4); if (esc) break;
        STEP(5); if (esc) break;
        STEP(6); if (esc) break;
        STEP(7); if (esc) break;
    }
#undef STEP

    if (!esc) {
        // Nothing escaped within the budget. Black here is a hole in the picture;
        // the far colour is the background the pixel belongs to, so the worst case
        // is a dark pixel.
        fragColor = vec4(vec3(0.0), 1.0) * qt_Opacity;
        return;
    }

    // Smooth escape count, with the per-loop drift removed so the palette lines
    // up exactly when the loop wraps.
    float n = iter - log2(0.5 * log2(m2));
    fragColor = vec4(palette(PAL_SCALE * uPalScale * (n - PAL_OFFSET - DRIFT * uPhase)).rgb, 1.0) * qt_Opacity;
}
