#version 440

// Generated by tools/gen.py -- do not edit by hand.
//
// Deep zoom at the Misiurewicz point
//   c = 0.44455687925504374932929635610683866299614893565870685865407151564251167851038720164415003160471913079612490459854965182260759568593104674331850085817778759040411648587799086896658256025581605777424483045276939487207306049658800804183027743893802627309240278820 + 0.40993310830098435048211659952036125134901073163739810789957994025749948234223445980178385006962165552546924023686408706365696873268047281369534771209567475388168416429625474170852429496809305419685917606745539241069578541945354030410551590637129102889405701750i
// preperiod 5, period 1, |lambda| = 2.062776,
// arg(lambda)/2pi = -0.093071786.
//
// The reference orbit is preperiodic, so it is a table of 6 values that
// repeats forever.  Perturbation then keeps every pixel's own arithmetic small:
// eps is the pixel's offset from the reference and starts at the view width, so
// the same float work renders the view at any depth.  The escape count is
// bounded because the reference never escapes, so raising the zoom costs
// nothing at all.

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;

    float uPhase;       // position in the loop, [0,1)
    float uAspect;      // height / width
    float uPalScale;    // multiplier on the band frequency baked in below

    vec4 uPal0;
    vec4 uPal1;
    vec4 uPal2;
    vec4 uPal3;
};

#define CYCLES 104          // whole periods actually iterated

// The point's own constants, baked in: nothing outside this file needs to know
// them, and the camera must match them exactly or the loop will not close.
#define OCT_PER_LOOP 1.0445870506220576    // log2 |lambda|, octaves of zoom per loop
#define ROT_PER_LOOP 0.0930717861750272    // 1 - arg(lambda)/2pi, turns per loop
#define PAL_SCALE 0.057274      // palette cycles per escape step, from the point's own range
#define PAL_OFFSET 20.467     // escape count that sits on the first palette stop
#define DRIFT 1         // escape steps gained over one loop, == period
#define HALF_W0 5.960464477539062e-07       // half width of the view at phase 0
#define TWO_PI 6.283185307179586

const vec2 ORB[6] = vec2[6](
    vec2(0.0, 0.0),
    vec2(0.4445568792550437, 0.40993310830098434),
    vec2(0.47414254486672075, 0.7744102749601953),
    vec2(0.06965675814380876, 1.1442948253821121),
    vec2(-0.8600017041861299, 0.5693488440946917),
    vec2(0.8600017041861299, -0.5693488440946917));

const float LOG2 = 0.6931471805599453;

vec4 palette(float t) {
    // Cyclic four stop ramp.
    float x = fract(t) * 4.0;
    vec4 a = uPal0, b = uPal1;
    if (x >= 3.0)      { a = uPal3; b = uPal0; x -= 3.0; }
    else if (x >= 2.0) { a = uPal2; b = uPal3; x -= 2.0; }
    else if (x >= 1.0) { a = uPal1; b = uPal2; x -= 1.0; }
    return mix(a, b, smoothstep(0.0, 1.0, x));
}

void main() {
    vec2 t = qt_TexCoord0;
    vec2 uv = vec2(t.x * 2.0 - 1.0, 1.0 - t.y * 2.0);
    uv.y *= uAspect;

    float halfw = HALF_W0 * exp2(-uPhase * OCT_PER_LOOP);

    float ang = uPhase * ROT_PER_LOOP * TWO_PI;
    float ca = cos(ang), sa = sin(ang);
    vec2 d = vec2(uv.x * ca - uv.y * sa, uv.x * sa + uv.y * ca) * halfw;

    vec2 e = vec2(0.0);
    float iter = 0.0;
    bool esc = false;
    float m2 = 0.0;
    vec2 zn;

#define STEP(I) { \
        zn = ORB[I]; \
        e = vec2(2.0 * (zn.x * e.x - zn.y * e.y) + e.x * e.x - e.y * e.y + d.x, \
                 2.0 * (zn.y * e.x + zn.x * e.y) + 2.0 * e.x * e.y + d.y); \
        iter += 1.0; \
        m2 = dot(e, e); \
        if (m2 > 65536.0) esc = true; \
    }

    // preperiod: a straight run of literal indices
    if (!esc) STEP(0);
    if (!esc) STEP(1);
    if (!esc) STEP(2);
    if (!esc) STEP(3);
    if (!esc) STEP(4);

    // then whole periods, again with literal indices, so nothing is indexed by a
    // computed value.  Breaking on escape matters: continuing to iterate an
    // escaped pixel squares it past float range and poisons the colour.
    for (int cycle = 0; cycle < CYCLES; cycle++) {
        STEP(5); if (esc) break;
    }
#undef STEP

    if (!esc) {
        fragColor = vec4(0.0, 0.0, 0.0, 1.0) * qt_Opacity;
        return;
    }

    // Smooth escape count, with the per-loop drift removed so the palette lines
    // up exactly when the loop wraps.
    float n = iter - log2(0.5 * log2(m2));
    fragColor = vec4(palette(PAL_SCALE * uPalScale * (n - PAL_OFFSET - DRIFT * uPhase)).rgb, 1.0) * qt_Opacity;
}
