#version 440

// Generated by tools/gen.py -- do not edit by hand.
//
// Deep zoom at the Misiurewicz point
//   c = -1.2392255553895674976657360754667509166108572168151787241314804443105267975636094717354068723652773650205090057098664937666667156365740329470999690891749280056025539680103173080123438452115885129445347540758724791251639332013188639602815784446099789872440283977 + 0.41260218160200354540879139839211208539965792697027802538916125944571540873271059317721611483599299088345352315784852623150036624121142319099853222058483550312514112983207169779889619446533539176190201042813908998041587538105779604299607089968436463551694852016i
// preperiod 2, period 3, |lambda| = 10.519982,
// arg(lambda)/2pi = 0.205741316.
//
// The reference orbit is preperiodic, so it is a table of 5 values that
// repeats forever.  Perturbation then keeps every pixel's own arithmetic small:
// eps is the pixel's offset from the reference and starts at the view width, so
// the same float work renders the view at any depth.  The escape count is
// bounded because the reference never escapes, so raising the zoom costs
// nothing at all.

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;

    float uPhase;       // position in the loop, [0,1)
    float uAspect;      // height / width
    float uPalScale;    // multiplier on the band frequency baked in below

    vec4 uPal0;
    vec4 uPal1;
    vec4 uPal2;
    vec4 uPal3;
};

#define CYCLES 27          // whole periods actually iterated

// The point's own constants, baked in: nothing outside this file needs to know
// them, and the camera must match them exactly or the loop will not close.
#define OCT_PER_LOOP 3.3950603363622256    // log2 |lambda|, octaves of zoom per loop
#define ROT_PER_LOOP 0.7942586837759125    // 1 - arg(lambda)/2pi, turns per loop
#define PAL_SCALE 0.079491      // palette cycles per escape step, from the point's own range
#define PAL_OFFSET 19.755     // escape count that sits on the first palette stop
#define DRIFT 3         // escape steps gained over one loop, == period
#define HALF_W0 5.960464477539062e-07       // half width of the view at phase 0
#define TWO_PI 6.283185307179586

const vec2 ORB[5] = vec2[5](
    vec2(0.0, 0.0),
    vec2(-1.2392255553895675, 0.41260218160200357),
    vec2(0.1262138614782818, -0.6100121536993766),
    vec2(-1.5954104442212604, 0.25861820266784064),
    vec2(1.2392255553895675, -0.41260218160200357));

const float LOG2 = 0.6931471805599453;

vec4 palette(float t) {
    // Cyclic four stop ramp.
    float x = fract(t) * 4.0;
    vec4 a = uPal0, b = uPal1;
    if (x >= 3.0)      { a = uPal3; b = uPal0; x -= 3.0; }
    else if (x >= 2.0) { a = uPal2; b = uPal3; x -= 2.0; }
    else if (x >= 1.0) { a = uPal1; b = uPal2; x -= 1.0; }
    return mix(a, b, smoothstep(0.0, 1.0, x));
}

void main() {
    vec2 t = qt_TexCoord0;
    vec2 uv = vec2(t.x * 2.0 - 1.0, 1.0 - t.y * 2.0);
    uv.y *= uAspect;

    float halfw = HALF_W0 * exp2(-uPhase * OCT_PER_LOOP);

    float ang = uPhase * ROT_PER_LOOP * TWO_PI;
    float ca = cos(ang), sa = sin(ang);
    vec2 d = vec2(uv.x * ca - uv.y * sa, uv.x * sa + uv.y * ca) * halfw;

    vec2 e = vec2(0.0);
    float iter = 0.0;
    bool esc = false;
    float m2 = 0.0;
    vec2 zn;

#define STEP(I) { \
        zn = ORB[I]; \
        e = vec2(2.0 * (zn.x * e.x - zn.y * e.y) + e.x * e.x - e.y * e.y + d.x, \
                 2.0 * (zn.y * e.x + zn.x * e.y) + 2.0 * e.x * e.y + d.y); \
        iter += 1.0; \
        m2 = dot(e, e); \
        if (m2 > 65536.0) esc = true; \
    }

    // preperiod: a straight run of literal indices
    if (!esc) STEP(0);
    if (!esc) STEP(1);

    // then whole periods, again with literal indices, so nothing is indexed by a
    // computed value.  Breaking on escape matters: continuing to iterate an
    // escaped pixel squares it past float range and poisons the colour.
    for (int cycle = 0; cycle < CYCLES; cycle++) {
        STEP(2); if (esc) break;
        STEP(3); if (esc) break;
        STEP(4); if (esc) break;
    }
#undef STEP

    if (!esc) {
        // Nothing escaped within the budget. Black here is a hole in the picture;
        // the far colour is the background the pixel belongs to, so the worst case
        // is a dark pixel.
        fragColor = vec4(vec3(0.0), 1.0) * qt_Opacity;
        return;
    }

    // Smooth escape count, with the per-loop drift removed so the palette lines
    // up exactly when the loop wraps.
    float n = iter - log2(0.5 * log2(m2));
    fragColor = vec4(palette(PAL_SCALE * uPalScale * (n - PAL_OFFSET - DRIFT * uPhase)).rgb, 1.0) * qt_Opacity;
}
