#version 440

// Generated by tools/gen.py -- do not edit by hand.
//
// Deep zoom into the Julia set of the Misiurewicz parameter
//   c = 0.41838862112929570651609350852712854162118749691173460153788565737015264428233545665256437107123206813859279649824775948392204286294276843144063632791074568455034930762285896864196812874293859566636824191912295049279072700292323711550448125380411941340450447941 + -0.67957631397475715694296884821779849839677793244604232229327003848684099891752203086447577913380674853655934482224150112467497241192310984146388846570064691492838024612219463063993907988650391783314638567980167925476640880729463528881128705464832243303461650968i
// preperiod 2, period 6, |lambda| = 68.121418,
// arg(lambda)/2pi = -0.289278193.
//
// The reference orbit is preperiodic, so it is a table of 8 values that
// repeats forever.  Perturbation then keeps every pixel's own arithmetic small:
// eps is the pixel's offset from the reference and starts at the view width, so
// the same float work renders the view at any depth.  The escape count is
// bounded because the reference never escapes, so raising the zoom costs
// nothing at all.
//
// The parameter is fixed and the pixel is the starting z, so the
// perturbation seeds with the pixel's own offset and nothing is added
// to it at any step.

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;

    float uPhase;       // position in the loop, [0,1)
    float uAspect;      // height / width
    float uPalScale;    // multiplier on the band frequency baked in below

    vec4 uPal0;
    vec4 uPal1;
    vec4 uPal2;
    vec4 uPal3;
};

#define CYCLES 51          // whole periods actually iterated

// The point's own constants, baked in: nothing outside this file needs to know
// them, and the camera must match them exactly or the loop will not close.
#define OCT_PER_LOOP 6.090036566996741    // log2 |lambda|, octaves of zoom per loop
#define ROT_PER_LOOP 0.289278193139622    // 1 - arg(lambda)/2pi, turns per loop
#define PAL_SCALE 0.08161      // palette cycles per escape step, from the point's own range
#define PAL_OFFSET 61.373     // escape count that sits on the first palette stop
#define DRIFT 18.0         // escape steps gained over one loop, == twice the period
#define HALF_W0 5.960464477539062e-07       // half width of the view at phase 0
#define TWO_PI 6.283185307179586

const vec2 ORB[8] = vec2[8](
    vec2(0.0, 0.0),
    vec2(0.4183886211292957, -0.6795763139747572),
    vec2(-0.08803853077501234, -0.722609225723738),
    vec2(0.5556179323305859, -0.3190580846508449),
    vec2(0.42023166280841195, -0.9425873150492904),
    vec2(-0.6274914588129897, -0.3414825964738308),
    vec2(0.39083268523641007, -1.0431276429125398),
    vec2(-0.7977246622769774, -0.022547017564934255));

const float LOG2 = 0.6931471805599453;

vec4 palette(float t) {
    // Cyclic four stop ramp.
    // 
    // z^d + c frames are a thin web in a large background, and a linear ramp
    // can only trade the background's darkness against the structure's contrast.
    // The gamma spends the low end of each cycle on the background and expands
    // the rest onto the structure, so both are available at once. Degree 2 is
    // a dense frame and needs none of this, so it keeps the linear ramp.
    float x = pow(fract(t), 1.7) * 4.0;
    vec4 a = uPal0, b = uPal1;
    if (x >= 3.0)      { a = uPal3; b = uPal0; x -= 3.0; }
    else if (x >= 2.0) { a = uPal2; b = uPal3; x -= 2.0; }
    else if (x >= 1.0) { a = uPal1; b = uPal2; x -= 1.0; }
    return mix(a, b, smoothstep(0.0, 1.0, x));
}

void main() {
    vec2 t = qt_TexCoord0;
    vec2 uv = vec2(t.x * 2.0 - 1.0, 1.0 - t.y * 2.0);
    uv.y *= uAspect;

    float halfw = HALF_W0 * exp2(-uPhase * OCT_PER_LOOP);

    float ang = uPhase * ROT_PER_LOOP * TWO_PI;
    float ca = cos(ang), sa = sin(ang);
    vec2 d = vec2(uv.x * ca - uv.y * sa, uv.x * sa + uv.y * ca) * halfw;

    vec2 e = d;
    float iter = 0.0;
    bool esc = false;
    float m2 = 0.0;
    vec2 zn;

#define STEP(I) { \
        zn = ORB[I]; \
        vec2 z2 = vec2(zn.x * zn.x - zn.y * zn.y, 2.0 * zn.x * zn.y); \
        vec2 e2 = vec2(e.x * e.x - e.y * e.y, 2.0 * e.x * e.y); \
        vec2 e3 = vec2(e2.x * e.x - e2.y * e.y, e2.x * e.y + e2.y * e.x); \
        vec2 t1 = vec2(z2.x * e.x - z2.y * e.y, z2.x * e.y + z2.y * e.x); \
        vec2 t2 = vec2(zn.x * e2.x - zn.y * e2.y, zn.x * e2.y + zn.y * e2.x); \
        e = vec2(3.0 * t1.x + 3.0 * t2.x + e3.x, 3.0 * t1.y + 3.0 * t2.y + e3.y); \
        iter += 1.0; \
        m2 = dot(e, e); \
        if (!(m2 <= 65536.0)) esc = true; \
    }

    // preperiod: a straight run of literal indices
    if (!esc) STEP(0);
    if (!esc) STEP(1);

    // then whole periods, again with literal indices, so nothing is indexed by a
    // computed value.  Breaking on escape matters: continuing to iterate an
    // escaped pixel squares it past float range and poisons the colour.
    for (int cycle = 0; cycle < CYCLES; cycle++) {
        STEP(2); if (esc) break;
        STEP(3); if (esc) break;
        STEP(4); if (esc) break;
        STEP(5); if (esc) break;
        STEP(6); if (esc) break;
        STEP(7); if (esc) break;
    }
#undef STEP

    if (!esc) {
        // Nothing escaped within the budget. Black here is a hole in the picture;
        // the far colour is the background the pixel belongs to, so the worst case
        // is a dark pixel.
        //
        // Degree 2 frames are dense and its interior is meant to be black,
        // so it keeps that.
        fragColor = vec4(vec3(0.0) + palette(0.0).rgb, 1.0) * qt_Opacity;
        return;
    }

    // Smooth escape count, with the per-loop drift removed so the palette lines
    // up exactly when the loop wraps.
    // The potential goes as log_degree, and this point is
    // degree 3, so the escape count is normalised by it.
    float n = iter - log2(0.5 * log2(m2)) / log2(3.0);
    fragColor = vec4(palette(PAL_SCALE * uPalScale * (n - PAL_OFFSET - DRIFT * uPhase)).rgb, 1.0) * qt_Opacity;
}
