#version 440

// Generated by tools/gen.py -- do not edit by hand.
//
// Deep zoom at the Misiurewicz point
//   c = -0.58907524906539345148563669834602486455255385275493705219166146599059328051588564933405011133126806987196717844151275140735835525144703078064767936680811994563538365629572392222432806369657924444258609973716970614300125547294899121485996056090979918152118030192 + 0.44326130090668261217851635545687863693278181899422579054517043041129399897577804885908881153902271990477102094372572544202386792251294776914391787622638771872056744552957733730600388696806099620158571160058900939188101218345176713912908383251509262977211653098i
// preperiod 2, period 5, |lambda| = 17.143486,
// arg(lambda)/2pi = -0.406483196.
//
// The reference orbit is preperiodic, so it is a table of 7 values that
// repeats forever.  Perturbation then keeps every pixel's own arithmetic small:
// eps is the pixel's offset from the reference and starts at the view width, so
// the same float work renders the view at any depth.  The escape count is
// bounded because the reference never escapes, so raising the zoom costs
// nothing at all.

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;

    float uPhase;       // position in the loop, [0,1)
    float uAspect;      // height / width
    float uPalScale;    // multiplier on the band frequency baked in below

    vec4 uPal0;
    vec4 uPal1;
    vec4 uPal2;
    vec4 uPal3;
};

#define CYCLES 46          // whole periods actually iterated

// The point's own constants, baked in: nothing outside this file needs to know
// them, and the camera must match them exactly or the loop will not close.
#define OCT_PER_LOOP 4.0995886250210365    // log2 |lambda|, octaves of zoom per loop
#define ROT_PER_LOOP 0.40648319574387615    // 1 - arg(lambda)/2pi, turns per loop
#define PAL_SCALE 0.035997      // palette cycles per escape step, from the point's own range
#define PAL_OFFSET 33.659     // escape count that sits on the first palette stop
#define DRIFT 5         // escape steps gained over one loop, == period
#define HALF_W0 4.6566128730773926e-09       // half width of the view at phase 0
#define TWO_PI 6.283185307179586

const vec2 ORB[7] = vec2[7](
    vec2(0.0, 0.0),
    vec2(-0.5890752490653934, 0.4432613009066826),
    vec2(-0.4462645031565438, 0.8176169084327113),
    vec2(0.21703027178369788, 0.3851766603704741),
    vec2(-0.6754491823873515, 0.44054401704400786),
    vec2(-0.503964940577739, 0.9607312476263),
    vec2(0.6784131716324221, 0.2885234799779348));

const float LOG2 = 0.6931471805599453;

vec4 palette(float t) {
    // Cyclic four stop ramp.
    // 
    // z^d + c frames are a thin web in a large background, and a linear ramp
    // can only trade the background's darkness against the structure's contrast.
    // The gamma spends the low end of each cycle on the background and expands
    // the rest onto the structure, so both are available at once. Degree 2 is
    // a dense frame and needs none of this, so it keeps the linear ramp.
    float x = pow(fract(t), 1.7) * 4.0;
    vec4 a = uPal0, b = uPal1;
    if (x >= 3.0)      { a = uPal3; b = uPal0; x -= 3.0; }
    else if (x >= 2.0) { a = uPal2; b = uPal3; x -= 2.0; }
    else if (x >= 1.0) { a = uPal1; b = uPal2; x -= 1.0; }
    return mix(a, b, smoothstep(0.0, 1.0, x));
}

void main() {
    vec2 t = qt_TexCoord0;
    vec2 uv = vec2(t.x * 2.0 - 1.0, 1.0 - t.y * 2.0);
    uv.y *= uAspect;

    float halfw = HALF_W0 * exp2(-uPhase * OCT_PER_LOOP);

    float ang = uPhase * ROT_PER_LOOP * TWO_PI;
    float ca = cos(ang), sa = sin(ang);
    vec2 d = vec2(uv.x * ca - uv.y * sa, uv.x * sa + uv.y * ca) * halfw;

    vec2 e = vec2(0.0);
    float iter = 0.0;
    bool esc = false;
    float m2 = 0.0;
    vec2 zn;

#define STEP(I) { \
        zn = ORB[I]; \
        vec2 z2 = vec2(zn.x * zn.x - zn.y * zn.y, 2.0 * zn.x * zn.y); \
        vec2 e2 = vec2(e.x * e.x - e.y * e.y, 2.0 * e.x * e.y); \
        vec2 e3 = vec2(e2.x * e.x - e2.y * e.y, e2.x * e.y + e2.y * e.x); \
        vec2 t1 = vec2(z2.x * e.x - z2.y * e.y, z2.x * e.y + z2.y * e.x); \
        vec2 t2 = vec2(zn.x * e2.x - zn.y * e2.y, zn.x * e2.y + zn.y * e2.x); \
        e = vec2(3.0 * t1.x + 3.0 * t2.x + e3.x + d.x, 3.0 * t1.y + 3.0 * t2.y + e3.y + d.y); \
        iter += 1.0; \
        m2 = dot(e, e); \
        if (!(m2 <= 65536.0)) esc = true; \
    }

    // preperiod: a straight run of literal indices
    if (!esc) STEP(0);
    if (!esc) STEP(1);

    // then whole periods, again with literal indices, so nothing is indexed by a
    // computed value.  Breaking on escape matters: continuing to iterate an
    // escaped pixel squares it past float range and poisons the colour.
    for (int cycle = 0; cycle < CYCLES; cycle++) {
        STEP(2); if (esc) break;
        STEP(3); if (esc) break;
        STEP(4); if (esc) break;
        STEP(5); if (esc) break;
        STEP(6); if (esc) break;
    }
#undef STEP

    if (!esc) {
        // Nothing escaped within the budget. Black here is a hole in the picture;
        // the far colour is the background the pixel belongs to, so the worst case
        // is a dark pixel.
        //
        // Degree 2 frames are dense and its interior is meant to be black,
        // so it keeps that.
        fragColor = vec4(vec3(0.0) + palette(0.0).rgb, 1.0) * qt_Opacity;
        return;
    }

    // Smooth escape count, with the per-loop drift removed so the palette lines
    // up exactly when the loop wraps.
    // The potential goes as log_degree, and this point is
    // degree 3, so the escape count is normalised by it.
    float n = iter - log2(0.5 * log2(m2)) / log2(3.0);
    fragColor = vec4(palette(PAL_SCALE * uPalScale * (n - PAL_OFFSET - DRIFT * uPhase)).rgb, 1.0) * qt_Opacity;
}
