#version 440

// Generated by tools/gen.py -- do not edit by hand.
//
// Deep zoom into the Julia set of the Misiurewicz parameter
//   c = -0.093649991860254574701124258539848140998071528978112934903822634865266988694362891303958108140218256439554816423817246743124016072446000449991443623574566884867996530419157441585948985751000559692019960373845837942555620081991517147760018612244585584882913434356 + -0.79886236585996252694997512102898408776636647499634731373004872032105282193388943749009898227531551761005723986832794472013128894667008556316394086351173469586055683587220241042362131623536202970913797647030581854383371439366824850692457032626069122197884589374i
// preperiod 4, period 6, |lambda| = 14.831193,
// arg(lambda)/2pi = -0.071832460.
//
// The reference orbit is preperiodic, so it is a table of 10 values that
// repeats forever.  Perturbation then keeps every pixel's own arithmetic small:
// eps is the pixel's offset from the reference and starts at the view width, so
// the same float work renders the view at any depth.  The escape count is
// bounded because the reference never escapes, so raising the zoom costs
// nothing at all.
//
// The parameter is fixed and the pixel is the starting z, so the
// perturbation seeds with the pixel's own offset and nothing is added
// to it at any step.

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;

    float uPhase;       // position in the loop, [0,1)
    float uAspect;      // height / width
    float uPalScale;    // multiplier on the band frequency baked in below

    vec4 uPal0;
    vec4 uPal1;
    vec4 uPal2;
    vec4 uPal3;
};

#define CYCLES 64          // whole periods actually iterated

// The point's own constants, baked in: nothing outside this file needs to know
// them, and the camera must match them exactly or the loop will not close.
#define OCT_PER_LOOP 3.8905627776208465    // log2 |lambda|, octaves of zoom per loop
#define ROT_PER_LOOP 0.07183245961442553    // 1 - arg(lambda)/2pi, turns per loop
#define PAL_SCALE 0.015366      // palette cycles per escape step, from the point's own range
#define PAL_OFFSET 125.055     // escape count that sits on the first palette stop
#define DRIFT 24.0         // escape steps gained over one loop, == twice the period
#define HALF_W0 5.960464477539062e-07       // half width of the view at phase 0
#define TWO_PI 6.283185307179586

const vec2 ORB[10] = vec2[10](
    vec2(0.0, 0.0),
    vec2(-0.09364999186025458, -0.7988623658599625),
    vec2(0.28011969956251687, -0.9872159373577297),
    vec2(0.4035014086475569, 0.19239396678937562),
    vec2(-0.10193130365119954, -0.7597989646920937),
    vec2(0.2037383566632455, -0.9744832476780453),
    vec2(0.5733387443737008, -0.07768048935478879),
    vec2(0.0025401027246489496, -0.8563480094918882),
    vec2(0.4440973140534915, -0.7924818127448602),
    vec2(-0.4035014086475569, -0.19239396678937562));

const float LOG2 = 0.6931471805599453;

vec4 palette(float t) {
    // Cyclic four stop ramp.
    float x = fract(t) * 4.0;
    vec4 a = uPal0, b = uPal1;
    if (x >= 3.0)      { a = uPal3; b = uPal0; x -= 3.0; }
    else if (x >= 2.0) { a = uPal2; b = uPal3; x -= 2.0; }
    else if (x >= 1.0) { a = uPal1; b = uPal2; x -= 1.0; }
    return mix(a, b, smoothstep(0.0, 1.0, x));
}

void main() {
    vec2 t = qt_TexCoord0;
    vec2 uv = vec2(t.x * 2.0 - 1.0, 1.0 - t.y * 2.0);
    uv.y *= uAspect;

    float halfw = HALF_W0 * exp2(-uPhase * OCT_PER_LOOP);

    float ang = uPhase * ROT_PER_LOOP * TWO_PI;
    float ca = cos(ang), sa = sin(ang);
    vec2 d = vec2(uv.x * ca - uv.y * sa, uv.x * sa + uv.y * ca) * halfw;

    vec2 e = d;
    float iter = 0.0;
    bool esc = false;
    float m2 = 0.0;
    vec2 zn;

#define STEP(I) { \
        zn = ORB[I]; \
        vec2 z2 = vec2(zn.x * zn.x - zn.y * zn.y, 2.0 * zn.x * zn.y); \
        vec2 z3 = vec2(z2.x * zn.x - z2.y * zn.y, z2.x * zn.y + z2.y * zn.x); \
        vec2 a = 1.0 * vec2(1.0); \
        a = vec2(a.x * e.x - a.y * e.y + 4.0 * zn.x, a.x * e.y + a.y * e.x + 4.0 * zn.y); \
        a = vec2(a.x * e.x - a.y * e.y + 6.0 * z2.x, a.x * e.y + a.y * e.x + 6.0 * z2.y); \
        a = vec2(a.x * e.x - a.y * e.y + 4.0 * z3.x, a.x * e.y + a.y * e.x + 4.0 * z3.y); \
        e = vec2(a.x * e.x - a.y * e.y, a.x * e.y + a.y * e.x); \
        iter += 1.0; \
        m2 = dot(e, e); \
        if (m2 > 65536.0) esc = true; \
    }

    // preperiod: a straight run of literal indices
    if (!esc) STEP(0);
    if (!esc) STEP(1);
    if (!esc) STEP(2);
    if (!esc) STEP(3);

    // then whole periods, again with literal indices, so nothing is indexed by a
    // computed value.  Breaking on escape matters: continuing to iterate an
    // escaped pixel squares it past float range and poisons the colour.
    for (int cycle = 0; cycle < CYCLES; cycle++) {
        STEP(4); if (esc) break;
        STEP(5); if (esc) break;
        STEP(6); if (esc) break;
        STEP(7); if (esc) break;
        STEP(8); if (esc) break;
        STEP(9); if (esc) break;
    }
#undef STEP

    if (!esc) {
        fragColor = vec4(0.0, 0.0, 0.0, 1.0) * qt_Opacity;
        return;
    }

    // Smooth escape count, with the per-loop drift removed so the palette lines
    // up exactly when the loop wraps.
    // The potential goes as log_degree, and this point is
    // degree 4, so the escape count is normalised by it.
    float n = iter - log2(0.5 * log2(m2)) / log2(4.0);
    fragColor = vec4(palette(PAL_SCALE * uPalScale * (n - PAL_OFFSET - DRIFT * uPhase)).rgb, 1.0) * qt_Opacity;
}
