#version 440

// Generated by tools/gen.py -- do not edit by hand.
//
// Deep zoom into the Julia set of the Misiurewicz parameter
//   c = -0.37565060471570237957411806595414836920923864856308712908231441537424551135296699862993951378191661084261252093542115655707094308106123622856954246978941439484639481332677460228187392245212580951246920857560405031181475442905375859508114228601469857039834873730 + 0.49598758748705844769044978089290803048581075116383471867666964219120481313031501177048451658418075989126832263507133256557530241623962300814807801046892377762172538778315133567880921607945726648276898181860295974420073032851859226707222226763103702891588161489i
// preperiod 2, period 4, |lambda| = 24.771291,
// arg(lambda)/2pi = 0.212504719.
//
// The reference orbit is preperiodic, so it is a table of 6 values that
// repeats forever.  Perturbation then keeps every pixel's own arithmetic small:
// eps is the pixel's offset from the reference and starts at the view width, so
// the same float work renders the view at any depth.  The escape count is
// bounded because the reference never escapes, so raising the zoom costs
// nothing at all.
//
// The parameter is fixed and the pixel is the starting z, so the
// perturbation seeds with the pixel's own offset and nothing is added
// to it at any step.

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;

    float uPhase;       // position in the loop, [0,1)
    float uAspect;      // height / width
    float uPalScale;    // multiplier on the band frequency baked in below

    vec4 uPal0;
    vec4 uPal1;
    vec4 uPal2;
    vec4 uPal3;
};

#define CYCLES 51          // whole periods actually iterated

// The point's own constants, baked in: nothing outside this file needs to know
// them, and the camera must match them exactly or the loop will not close.
#define OCT_PER_LOOP 4.630597183088109    // log2 |lambda|, octaves of zoom per loop
#define ROT_PER_LOOP 0.7874952805044128    // 1 - arg(lambda)/2pi, turns per loop
#define PAL_SCALE 0.029377      // palette cycles per escape step, from the point's own range
#define PAL_OFFSET 71.813     // escape count that sits on the first palette stop
#define DRIFT 16.0         // escape steps gained over one loop, == twice the period
#define HALF_W0 5.960464477539062e-07       // half width of the view at phase 0
#define TWO_PI 6.283185307179586

const vec2 ORB[6] = vec2[6](
    vec2(0.0, 0.0),
    vec2(-0.3756506047157024, 0.49598758748705846),
    vec2(-0.503506271460071, 0.5741594142847996),
    vec2(-0.7041519743882702, 0.5840342514621324),
    vec2(-1.0282105316577874, 0.2414508624207962),
    vec2(0.3756506047157024, -0.49598758748705846));

const float LOG2 = 0.6931471805599453;

vec4 palette(float t) {
    // Cyclic four stop ramp.
    float x = fract(t) * 4.0;
    vec4 a = uPal0, b = uPal1;
    if (x >= 3.0)      { a = uPal3; b = uPal0; x -= 3.0; }
    else if (x >= 2.0) { a = uPal2; b = uPal3; x -= 2.0; }
    else if (x >= 1.0) { a = uPal1; b = uPal2; x -= 1.0; }
    return mix(a, b, smoothstep(0.0, 1.0, x));
}

void main() {
    vec2 t = qt_TexCoord0;
    vec2 uv = vec2(t.x * 2.0 - 1.0, 1.0 - t.y * 2.0);
    uv.y *= uAspect;

    float halfw = HALF_W0 * exp2(-uPhase * OCT_PER_LOOP);

    float ang = uPhase * ROT_PER_LOOP * TWO_PI;
    float ca = cos(ang), sa = sin(ang);
    vec2 d = vec2(uv.x * ca - uv.y * sa, uv.x * sa + uv.y * ca) * halfw;

    vec2 e = d;
    float iter = 0.0;
    bool esc = false;
    float m2 = 0.0;
    vec2 zn;

#define STEP(I) { \
        zn = ORB[I]; \
        vec2 z2 = vec2(zn.x * zn.x - zn.y * zn.y, 2.0 * zn.x * zn.y); \
        vec2 z3 = vec2(z2.x * zn.x - z2.y * zn.y, z2.x * zn.y + z2.y * zn.x); \
        vec2 a = 1.0 * vec2(1.0); \
        a = vec2(a.x * e.x - a.y * e.y + 4.0 * zn.x, a.x * e.y + a.y * e.x + 4.0 * zn.y); \
        a = vec2(a.x * e.x - a.y * e.y + 6.0 * z2.x, a.x * e.y + a.y * e.x + 6.0 * z2.y); \
        a = vec2(a.x * e.x - a.y * e.y + 4.0 * z3.x, a.x * e.y + a.y * e.x + 4.0 * z3.y); \
        e = vec2(a.x * e.x - a.y * e.y, a.x * e.y + a.y * e.x); \
        iter += 1.0; \
        m2 = dot(e, e); \
        if (m2 > 65536.0) esc = true; \
    }

    // preperiod: a straight run of literal indices
    if (!esc) STEP(0);
    if (!esc) STEP(1);

    // then whole periods, again with literal indices, so nothing is indexed by a
    // computed value.  Breaking on escape matters: continuing to iterate an
    // escaped pixel squares it past float range and poisons the colour.
    for (int cycle = 0; cycle < CYCLES; cycle++) {
        STEP(2); if (esc) break;
        STEP(3); if (esc) break;
        STEP(4); if (esc) break;
        STEP(5); if (esc) break;
    }
#undef STEP

    if (!esc) {
        fragColor = vec4(0.0, 0.0, 0.0, 1.0) * qt_Opacity;
        return;
    }

    // Smooth escape count, with the per-loop drift removed so the palette lines
    // up exactly when the loop wraps.
    // The potential goes as log_degree, and this point is
    // degree 4, so the escape count is normalised by it.
    float n = iter - log2(0.5 * log2(m2)) / log2(4.0);
    fragColor = vec4(palette(PAL_SCALE * uPalScale * (n - PAL_OFFSET - DRIFT * uPhase)).rgb, 1.0) * qt_Opacity;
}
