#version 440

// Generated by tools/gen.py -- do not edit by hand.
//
// Deep zoom at the Misiurewicz point
//   c = -0.71758874450152375619948498065786511441133187388021532222840196162131442850861462817223511981396674484758876311960786983933793167612128587178312343737230981914312869864479272386836783674518922791249187408617869990202929308398774496488483881236210281209942425100 + -0.44041060756184276423755562850464938923743992927277721687247706250936387103825028164668847320400630056605433312756891460073440725871119204984498430169951647801935635218609811481046131934745444357425291340879075528512493227197241657921873767394584026770950068562i
// preperiod 2, period 5, |lambda| = 43.657240,
// arg(lambda)/2pi = -0.090068660.
//
// The reference orbit is preperiodic, so it is a table of 7 values that
// repeats forever.  Perturbation then keeps every pixel's own arithmetic small:
// eps is the pixel's offset from the reference and starts at the view width, so
// the same float work renders the view at any depth.  The escape count is
// bounded because the reference never escapes, so raising the zoom costs
// nothing at all.

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;

    float uPhase;       // position in the loop, [0,1)
    float uAspect;      // height / width
    float uPalScale;    // multiplier on the band frequency baked in below

    vec4 uPal0;
    vec4 uPal1;
    vec4 uPal2;
    vec4 uPal3;
};

#define CYCLES 45          // whole periods actually iterated

// The point's own constants, baked in: nothing outside this file needs to know
// them, and the camera must match them exactly or the loop will not close.
#define OCT_PER_LOOP 5.448149017912768    // log2 |lambda|, octaves of zoom per loop
#define ROT_PER_LOOP 0.09006865982240364    // 1 - arg(lambda)/2pi, turns per loop
#define PAL_SCALE 0.037175      // palette cycles per escape step, from the point's own range
#define PAL_OFFSET 25.075     // escape count that sits on the first palette stop
#define DRIFT 5         // escape steps gained over one loop, == period
#define HALF_W0 4.6566128730773926e-09       // half width of the view at phase 0
#define TWO_PI 6.283185307179586

const vec2 ORB[7] = vec2[7](
    vec2(0.0, 0.0),
    vec2(-0.7175887445015238, -0.44041060756184275),
    vec2(-1.0140748389721657, -0.03465860884222715),
    vec2(0.33250022670073515, -0.2960084969148208),
    vec2(-0.755810976219115, -0.44944006957092225),
    vec2(-1.0428022413384823, 0.06131932798448648),
    vec2(0.44041060756184275, -0.7175887445015238));

const float LOG2 = 0.6931471805599453;

vec4 palette(float t) {
    // Cyclic four stop ramp.
    // 
    // z^d + c frames are a thin web in a large background, and a linear ramp
    // can only trade the background's darkness against the structure's contrast.
    // The gamma spends the low end of each cycle on the background and expands
    // the rest onto the structure, so both are available at once. Degree 2 is
    // a dense frame and needs none of this, so it keeps the linear ramp.
    float x = pow(fract(t), 1.7) * 4.0;
    vec4 a = uPal0, b = uPal1;
    if (x >= 3.0)      { a = uPal3; b = uPal0; x -= 3.0; }
    else if (x >= 2.0) { a = uPal2; b = uPal3; x -= 2.0; }
    else if (x >= 1.0) { a = uPal1; b = uPal2; x -= 1.0; }
    return mix(a, b, smoothstep(0.0, 1.0, x));
}

void main() {
    vec2 t = qt_TexCoord0;
    vec2 uv = vec2(t.x * 2.0 - 1.0, 1.0 - t.y * 2.0);
    uv.y *= uAspect;

    float halfw = HALF_W0 * exp2(-uPhase * OCT_PER_LOOP);

    float ang = uPhase * ROT_PER_LOOP * TWO_PI;
    float ca = cos(ang), sa = sin(ang);
    vec2 d = vec2(uv.x * ca - uv.y * sa, uv.x * sa + uv.y * ca) * halfw;

    vec2 e = vec2(0.0);
    float iter = 0.0;
    bool esc = false;
    float m2 = 0.0;
    vec2 zn;

#define STEP(I) { \
        zn = ORB[I]; \
        vec2 z2 = vec2(zn.x * zn.x - zn.y * zn.y, 2.0 * zn.x * zn.y); \
        vec2 z3 = vec2(z2.x * zn.x - z2.y * zn.y, z2.x * zn.y + z2.y * zn.x); \
        vec2 e2 = vec2(e.x * e.x - e.y * e.y, 2.0 * e.x * e.y); \
        vec2 e3 = vec2(e2.x * e.x - e2.y * e.y, e2.x * e.y + e2.y * e.x); \
        vec2 e4 = vec2(e3.x * e.x - e3.y * e.y, e3.x * e.y + e3.y * e.x); \
        vec2 t1 = vec2(z3.x * e.x - z3.y * e.y, z3.x * e.y + z3.y * e.x); \
        vec2 t2 = vec2(z2.x * e2.x - z2.y * e2.y, z2.x * e2.y + z2.y * e2.x); \
        vec2 t3 = vec2(zn.x * e3.x - zn.y * e3.y, zn.x * e3.y + zn.y * e3.x); \
        e = vec2(4.0 * t1.x + 6.0 * t2.x + 4.0 * t3.x + e4.x + d.x, 4.0 * t1.y + 6.0 * t2.y + 4.0 * t3.y + e4.y + d.y); \
        iter += 1.0; \
        m2 = dot(e, e); \
        if (!(m2 <= 65536.0)) esc = true; \
    }

    // preperiod: a straight run of literal indices
    if (!esc) STEP(0);
    if (!esc) STEP(1);

    // then whole periods, again with literal indices, so nothing is indexed by a
    // computed value.  Breaking on escape matters: continuing to iterate an
    // escaped pixel squares it past float range and poisons the colour.
    for (int cycle = 0; cycle < CYCLES; cycle++) {
        STEP(2); if (esc) break;
        STEP(3); if (esc) break;
        STEP(4); if (esc) break;
        STEP(5); if (esc) break;
        STEP(6); if (esc) break;
    }
#undef STEP

    if (!esc) {
        // Nothing escaped within the budget. Black here is a hole in the picture;
        // the far colour is the background the pixel belongs to, so the worst case
        // is a dark pixel.
        //
        // Degree 2 frames are dense and its interior is meant to be black,
        // so it keeps that.
        fragColor = vec4(vec3(0.0) + palette(0.0).rgb, 1.0) * qt_Opacity;
        return;
    }

    // Smooth escape count, with the per-loop drift removed so the palette lines
    // up exactly when the loop wraps.
    // The potential goes as log_degree, and this point is
    // degree 4, so the escape count is normalised by it.
    float n = iter - log2(0.5 * log2(m2)) / log2(4.0);
    fragColor = vec4(palette(PAL_SCALE * uPalScale * (n - PAL_OFFSET - DRIFT * uPhase)).rgb, 1.0) * qt_Opacity;
}
