#version 440

// Generated by tools/gen.py -- do not edit by hand.
//
// Deep zoom into the Julia set of the Misiurewicz parameter
//   c = -1.4261061293843750916432732978430452003392906552456589485150628911698652550297647830929007184839245750490147672402740743965648873960983087248065372805532260663490761613033794394183154730113956680512946185920204511525186120437476652264923238495322880157087322784 + 0.15385898610026291761919237511451754261494042619791716893469639871929500884831955257360356385300640025638958748380672186637685822496823969308586460047076097638548014227063674388678665059981512261284906355847022098918559955024169421212205623924036566849945042110i
// preperiod 4, period 4, |lambda| = 30.722844,
// arg(lambda)/2pi = -0.201787558.
//
// The reference orbit is preperiodic, so it is a table of 8 values that
// repeats forever.  Perturbation then keeps every pixel's own arithmetic small:
// eps is the pixel's offset from the reference and starts at the view width, so
// the same float work renders the view at any depth.  The escape count is
// bounded because the reference never escapes, so raising the zoom costs
// nothing at all.
//
// The parameter is fixed and the pixel is the starting z, so the
// perturbation seeds with the pixel's own offset and nothing is added
// to it at any step.

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;

    float uPhase;       // position in the loop, [0,1)
    float uAspect;      // height / width
    float uPalScale;    // multiplier on the band frequency baked in below

    vec4 uPal0;
    vec4 uPal1;
    vec4 uPal2;
    vec4 uPal3;
};

#define CYCLES 23          // whole periods actually iterated

// The point's own constants, baked in: nothing outside this file needs to know
// them, and the camera must match them exactly or the loop will not close.
#define OCT_PER_LOOP 4.941239865881315    // log2 |lambda|, octaves of zoom per loop
#define ROT_PER_LOOP 0.2017875583260622    // 1 - arg(lambda)/2pi, turns per loop
#define PAL_SCALE 0.067295      // palette cycles per escape step, from the point's own range
#define PAL_OFFSET 34.553     // escape count that sits on the first palette stop
#define DRIFT 8.0         // escape steps gained over one loop, == twice the period
#define HALF_W0 5.960464477539062e-07       // half width of the view at phase 0
#define TWO_PI 6.283185307179586

const vec2 ORB[8] = vec2[8](
    vec2(0.0, 0.0),
    vec2(-1.426106129384375, 0.1538589861002629),
    vec2(0.583999975279508, -0.2849795001766377),
    vec2(-1.1662634737788353, -0.17899705601638302),
    vec2(-0.09797558517623098, 0.5713744427919663),
    vec2(-1.74297566796958, 0.04189749532569131),
    vec2(1.6101026496350626, 0.007806356297164586),
    vec2(1.1662634737788353, 0.17899705601638302));

const float LOG2 = 0.6931471805599453;

vec4 palette(float t) {
    // Cyclic four stop ramp.
    float x = fract(t) * 4.0;
    vec4 a = uPal0, b = uPal1;
    if (x >= 3.0)      { a = uPal3; b = uPal0; x -= 3.0; }
    else if (x >= 2.0) { a = uPal2; b = uPal3; x -= 2.0; }
    else if (x >= 1.0) { a = uPal1; b = uPal2; x -= 1.0; }
    return mix(a, b, smoothstep(0.0, 1.0, x));
}

void main() {
    vec2 t = qt_TexCoord0;
    vec2 uv = vec2(t.x * 2.0 - 1.0, 1.0 - t.y * 2.0);
    uv.y *= uAspect;

    float halfw = HALF_W0 * exp2(-uPhase * OCT_PER_LOOP);

    float ang = uPhase * ROT_PER_LOOP * TWO_PI;
    float ca = cos(ang), sa = sin(ang);
    vec2 d = vec2(uv.x * ca - uv.y * sa, uv.x * sa + uv.y * ca) * halfw;

    vec2 e = d;
    float iter = 0.0;
    bool esc = false;
    float m2 = 0.0;
    vec2 zn;

#define STEP(I) { \
        zn = ORB[I]; \
        e = vec2(2.0 * (zn.x * e.x - zn.y * e.y) + e.x * e.x - e.y * e.y, \
                 2.0 * (zn.y * e.x + zn.x * e.y) + 2.0 * e.x * e.y); \
        iter += 1.0; \
        m2 = dot(e, e); \
        if (m2 > 65536.0) esc = true; \
    }

    // preperiod: a straight run of literal indices
    if (!esc) STEP(0);
    if (!esc) STEP(1);
    if (!esc) STEP(2);
    if (!esc) STEP(3);

    // then whole periods, again with literal indices, so nothing is indexed by a
    // computed value.  Breaking on escape matters: continuing to iterate an
    // escaped pixel squares it past float range and poisons the colour.
    for (int cycle = 0; cycle < CYCLES; cycle++) {
        STEP(4); if (esc) break;
        STEP(5); if (esc) break;
        STEP(6); if (esc) break;
        STEP(7); if (esc) break;
    }
#undef STEP

    if (!esc) {
        fragColor = vec4(0.0, 0.0, 0.0, 1.0) * qt_Opacity;
        return;
    }

    // Smooth escape count, with the per-loop drift removed so the palette lines
    // up exactly when the loop wraps.
    float n = iter - log2(0.5 * log2(m2));
    fragColor = vec4(palette(PAL_SCALE * uPalScale * (n - PAL_OFFSET - DRIFT * uPhase)).rgb, 1.0) * qt_Opacity;
}
