#!/usr/bin/env python3
"""Generate the Mandelbrot deep-zoom fragment shader for a Misiurewicz point.

The camera walks one renormalisation period: zoom by |lambda| while rotating by
-arg(lambda).  That maps the picture onto itself, so the animation loops with no
seam while the iteration budget stays fixed.

usage: gen.py <point.json> <out.frag> [julia]

With no mode it renders the Mandelbrot set at the point; with `julia` it renders
the Julia set of the same parameter. The camera, the orbit and every baked
constant are identical -- only where the perturbation comes from differs.
"""
import json
import sys

# How much of each palette cycle to spend on the background. 1.0 is linear.
RAMP_GAMMA = 1.7


def binom(n, k):
    r = 1
    for i in range(1, k + 1):
        r = r * (n - k + i) // i
    return r


def step_statements(degree, dc):
    """The perturbation step: e <- sum_j C(d,j) Z^(d-j) e^j + dc.

    Returns GLSL statements, not an expression, because GLSL multiplies vec2
    component-wise: `zn * zn` is (zn.x*zn.x, zn.y*zn.y), NOT the complex square.
    Every product has to be written out.

    `!(m2 <= cap)` is the escape test for these degrees, not `m2 > cap`: the
    products reach float32's range and Inf - Inf is NaN, for which both
    comparisons are false. Testing the way round that lets NaN through leaves an
    overflowed pixel unescaped, and the shader draws it black -- which is the
    black disc in the middle of the degree-4 Julia renderings.

    No accumulator either. Horner chains dependent float operations with a
    cancellation in each; the degree-2 step that works is a single expression, so
    each product is its own temporary here and the sum happens once.

    Degree 2 keeps the exact text it has always had, so the twelve shipped points
    regenerate byte-identical shaders rather than merely equivalent ones.
    """
    if degree == 2:
        return ("e = vec2(2.0 * (zn.x * e.x - zn.y * e.y) + e.x * e.x - e.y * e.y%(addx)s, \\\n"
                "                 2.0 * (zn.y * e.x + zn.x * e.y) + 2.0 * e.x * e.y%(addy)s);"
                % dict(addx=("" if dc else " + d.x"), addy=("" if dc else " + d.y")))

    lines = []
    zp = {1: "zn"}
    lines.append("vec2 z2 = vec2(zn.x * zn.x - zn.y * zn.y, 2.0 * zn.x * zn.y);")
    zp[2] = "z2"
    for k in range(3, degree):
        prev = zp[k - 1]
        zp[k] = "z%d" % k
        lines.append("vec2 %s = vec2(%s.x * zn.x - %s.y * zn.y,"
                     " %s.x * zn.y + %s.y * zn.x);" % (zp[k], prev, prev, prev, prev))

    ep = {1: "e"}
    lines.append("vec2 e2 = vec2(e.x * e.x - e.y * e.y, 2.0 * e.x * e.y);")
    ep[2] = "e2"
    for k in range(3, degree + 1):
        prev = ep[k - 1]
        ep[k] = "e%d" % k
        lines.append("vec2 %s = vec2(%s.x * e.x - %s.y * e.y,"
                     " %s.x * e.y + %s.y * e.x);" % (ep[k], prev, prev, prev, prev))

    xs, ys = [], []
    for j in range(1, degree + 1):
        coef = float(binom(degree, j))
        zpow = degree - j
        if zpow == 0:
            name = ep[j]
        else:
            name = "t%d" % j
            lines.append("vec2 %s = vec2(%s.x * %s.x - %s.y * %s.y,"
                         " %s.x * %s.y + %s.y * %s.x);"
                         % (name, zp[zpow], ep[j], zp[zpow], ep[j],
                            zp[zpow], ep[j], zp[zpow], ep[j]))
        xs.append("%r * %s.x" % (coef, name) if coef != 1.0 else "%s.x" % name)
        ys.append("%r * %s.y" % (coef, name) if coef != 1.0 else "%s.y" % name)

    lines.append("e = vec2(%s%s, %s%s);"
                 % (" + ".join(xs), "" if dc else " + d.x",
                    " + ".join(ys), "" if dc else " + d.y"))
    return " \\\n        ".join(lines)



def main():
    with open(sys.argv[1]) as fh:
        pt = json.load(fh)
    out = sys.argv[2]
    julia = len(sys.argv) > 3 and sys.argv[3].startswith("j")

    orb = [[float(v[0]), float(v[1])] for v in pt["orbit"]]
    q, p = int(pt["q"]), int(pt["p"])
    assert len(orb) == q + p, (len(orb), q, p)
    maxiter = int(pt["maxiter"])

    # The Julia rendering carries its own measured budget, drift and palette
    # anchor, because its escape counts run about twice as high. Without the
    # block the Mandelbrot values are used and the picture is geometrically
    # right but coloured wrong.
    variant = pt.get("julia") if julia and isinstance(pt.get("julia"), dict) else None
    if variant:
        maxiter = int(variant["maxiter"])
    degree = int(pt.get("power", 2))
    cycles = max(1, (maxiter - q) // p)
    total = q + cycles * p

    orbtext = ",\n".join("    vec2(%r, %r)" % (v[0], v[1]) for v in orb)

    src = """#version 440

// Generated by tools/gen.py -- do not edit by hand.
//
// Deep zoom %(what)s
//   c = %(cre)s + %(cim)si
// preperiod %(q)d, period %(p)d, |lambda| = %(abslam).6f,
// arg(lambda)/2pi = %(arglam).9f.
//
// The reference orbit is preperiodic, so it is a table of %(norb)d values that
// repeats forever.  Perturbation then keeps every pixel's own arithmetic small:
// eps is the pixel's offset from the reference and starts at the view width, so
// the same float work renders the view at any depth.  The escape count is
// bounded because the reference never escapes, so raising the zoom costs
// nothing at all.%(note)s

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;

    float uPhase;       // position in the loop, [0,1)
    float uAspect;      // height / width
    float uPalScale;    // multiplier on the band frequency baked in below

    vec4 uPal0;
    vec4 uPal1;
    vec4 uPal2;
    vec4 uPal3;
};

#define CYCLES %(cycles)d          // whole periods actually iterated

// The point's own constants, baked in: nothing outside this file needs to know
// them, and the camera must match them exactly or the loop will not close.
#define OCT_PER_LOOP %(oct)r    // log2 |lambda|, octaves of zoom per loop
#define ROT_PER_LOOP %(rot)r    // 1 - arg(lambda)/2pi, turns per loop
#define PAL_SCALE %(palscale)r      // palette cycles per escape step, from the point's own range
#define PAL_OFFSET %(paloffset)r     // escape count that sits on the first palette stop
#define DRIFT %(drift)r         // escape steps gained over one loop, %(driftnote)s
#define HALF_W0 %(halfw)r       // half width of the view at phase 0
#define TWO_PI 6.283185307179586

const vec2 ORB[%(norb)d] = vec2[%(norb)d](
%(orbtext)s);

const float LOG2 = 0.6931471805599453;

vec4 palette(float t) {
    // Cyclic four stop ramp.%(rampnote)s
    float x = %(ramp)s;
    vec4 a = uPal0, b = uPal1;
    if (x >= 3.0)      { a = uPal3; b = uPal0; x -= 3.0; }
    else if (x >= 2.0) { a = uPal2; b = uPal3; x -= 2.0; }
    else if (x >= 1.0) { a = uPal1; b = uPal2; x -= 1.0; }
    return mix(a, b, smoothstep(0.0, 1.0, x));
}

void main() {
    vec2 t = qt_TexCoord0;
    vec2 uv = vec2(t.x * 2.0 - 1.0, 1.0 - t.y * 2.0);
    uv.y *= uAspect;

    float halfw = HALF_W0 * exp2(-uPhase * OCT_PER_LOOP);

    float ang = uPhase * ROT_PER_LOOP * TWO_PI;
    float ca = cos(ang), sa = sin(ang);
    vec2 d = vec2(uv.x * ca - uv.y * sa, uv.x * sa + uv.y * ca) * halfw;

    vec2 e = %(init)s;
    float iter = 0.0;
    bool esc = false;
    float m2 = 0.0;
    vec2 zn;

#define STEP(I) { \\
        zn = ORB[I]; \\
        %(step)s \\
        iter += 1.0; \\
        m2 = dot(e, e); \\
        if (%(esctest)s) esc = true; \\
    }

    // preperiod: a straight run of literal indices
%(pre)s
    // then whole periods, again with literal indices, so nothing is indexed by a
    // computed value.  Breaking on escape matters: continuing to iterate an
    // escaped pixel squares it past float range and poisons the colour.
    for (int cycle = 0; cycle < CYCLES; cycle++) {
%(body)s    }
#undef STEP

    if (!esc) {
        // Nothing escaped within the budget. Black here is a hole in the picture;
        // the far colour is the background the pixel belongs to, so the worst case
        // is a dark pixel.%(d2black)s
        fragColor = vec4(vec3(0.0)%(nonesc)s, 1.0) * qt_Opacity;
        return;
    }

    // Smooth escape count, with the per-loop drift removed so the palette lines
    // up exactly when the loop wraps.
%(degreeComment)s    float n = iter - log2(0.5 * log2(m2))%(degreeNorm)s;
    fragColor = vec4(palette(PAL_SCALE * uPalScale * (n - PAL_OFFSET - DRIFT * uPhase)).rgb, 1.0) * qt_Opacity;
}
""" % dict(
        cre=pt["c_re"], cim=pt["c_im"], q=q, p=p,
        abslam=pt["abs_lambda"], arglam=pt["arg_lambda_turns"],
        norb=len(orb), orbtext=orbtext, maxiter=maxiter, cycles=cycles,
        what=("into the Julia set of the Misiurewicz parameter" if julia
              else "at the Misiurewicz point"),
        note=("\n//\n// The parameter is fixed and the pixel is the starting z, so the"
              "\n// perturbation seeds with the pixel's own offset and nothing is added"
              "\n// to it at any step." if julia else ""),
        init=("d" if julia else "vec2(0.0)"),
        step=step_statements(degree, julia),
        ramp=("fract(t) * 4.0" if degree == 2
              else "pow(fract(t), %r) * 4.0" % RAMP_GAMMA),
        rampnote=("" if degree == 2 else
                  "\n    // \n"
                  "    // z^d + c frames are a thin web in a large background, and a linear ramp\n"
                  "    // can only trade the background's darkness against the structure's contrast.\n"
                  "    // The gamma spends the low end of each cycle on the background and expands\n"
                  "    // the rest onto the structure, so both are available at once. Degree 2 is\n"
                  "    // a dense frame and needs none of this, so it keeps the linear ramp."),
        degreeNorm=("" if degree == 2 else " / log2(%d.0)" % degree),
        esctest=("m2 > 65536.0" if degree == 2 else "!(m2 <= 65536.0)"),
        nonesc=("" if degree == 2 else " + palette(0.0).rgb"),
        d2black=("" if degree == 2 else
                 "\n        //\n"
                 "        // Degree 2 frames are dense and its interior is meant to be black,\n"
                 "        // so it keeps that."),
        degreeComment=("" if degree == 2 else
                       "    // The potential goes as log_degree, and this point is\n"
                       "    // degree %d, so the escape count is normalised by it.\n" % degree),
        oct=pt["oct_per_loop"], rot=pt["rot_per_loop"],
        # Both measured per variant. The Mandelbrot rendering gains the period
        # per loop and anchors its palette on its own escape floor; the Julia one
        # gains twice the period and needs its own anchor, or the far field comes
        # out mid-ramp and floods the picture with the wrong colour.
        drift=variant["drift"] if variant else p,
        driftnote=("== twice the period" if julia else "== period"),
        # The Julia rendering can carry its own start depth: its offset is the
        # pixel's position within the view, so a view narrower than the reference's
        # float32 rounding error renders noise.
        halfw=(variant["half_w0"] if variant and "half_w0" in variant
               else pt["half_w0"]),
        palscale=variant["pal_scale"] if variant else pt["pal_scale"],
        paloffset=variant["pal_offset"] if variant else pt["pal_offset"],
        pre="".join("    if (!esc) STEP(%d);\n" % i for i in range(q)),
        body="".join("        STEP(%d); if (esc) break;\n" % (q + j) for j in range(p)),
    )
    with open(out, "w") as fh:
        fh.write(src)
    print("wrote %s: degree %d, %d steps per pixel (%d cycles of %d after %d preperiod)"
          % (out, degree, total, cycles, p, q))


main()
